server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://10.22.66.39:3306/prt?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: $0uthPark
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 100
      minimum-idle: 5
      pool-name: HikariPool
      max-life-time: 20000
    initialization-mode: never
  jpa:
    open-in-view: false
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    tomcat:
      initial-size: 10
      max-active: 10000
      max-wait: 30000
      max-idle: 50
      min-idle: 10

demo:
  security:
    aes:
      secretKey: "dTc9lqnpKiL6MlwS1ajZzphq9yh2lnZV"

log4j:
  configurationFile: /home/pond/set/test_java/match_information/src/main/resources/application.yaml
